// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.confidentialledger;

import com.azure.core.util.ServiceVersion;

/** Service version of AzureConfidentialLedgerClient. */
public enum AzureConfidentialLedgerServiceVersion implements ServiceVersion {
    /** Enum value 2022-05-13. */
    V2022_05_13("2022-05-13");

    private final String version;

    AzureConfidentialLedgerServiceVersion(String version) {
        this.version = version;
    }

    /** {@inheritDoc} */
    @Override
    public String getVersion() {
        return this.version;
    }

    /**
     * Gets the latest service version supported by this client library.
     *
     * @return The latest {@link AzureConfidentialLedgerServiceVersion}.
     */
    public static AzureConfidentialLedgerServiceVersion getLatest() {
        return V2022_05_13;
    }
}
